### ISSUE TITLE
arecord: set_params:1305: Channels count non available ERROR:recorder:Microphone recorder died unexpectedly, aborting...

### ISSUE THREAD

**Issue by titusece** [senyoltw/DANBOARD#1]
Hello Expert,
I gone through your wonderful code, it looks really cool.
I am trying to make it work the dialogflow with my raspberry pi board. (not AIY KIT board)
Have installed the necessary packages, and using USB sound card on raspberry pi board.
Able to record the audio using the following command.
`arecord --device=plughw:1,0 --format S16_LE --rate 44100 -c2 test.wav 
`
And getting the following errors while running your demo code.
```
(env) pi@raspberrypi:~/DANBOARD $ python3 dialogflow_audio_demo.py mod/resources/alexa.umdl
INFO:Speak Wake Word and speak
arecord: set_params:1305: Channels count non available
ERROR:recorder:Microphone recorder died unexpectedly, aborting...
```
Please let me know if need any about my board setup.
My aim is that I would like to run python based dialog flow examples on raspberry pi (lite version image)
Can you please me to sort out the issue ?
Thanks for the help.

**Comment by senyoltw** [comment]
Can you work voice kit default program on your board  ?
If it will not work, your audio configure wrong.
https://github.com/google/aiyprojects-raspbian/blob/voicekit/src/assistant_library_demo.py

arecord err may be resolve make .asoundrc.
https://developers.google.com/assistant/sdk/guides/service/python/embed/audio

**Comment by titusece** [comment]
Thanks for the reply.
Got the below errors and warning while running the demo.
Can you please let me know what could be the problem ?
```
(env) pi@raspberrypi:~/AIY-projects-python/src/examples/voice $ python assistant_library_demo.py
ALSA lib pcm.c:8382:(snd_pcm_set_params) Sample format not available for CAPTURE: Invalid argument
[9126:9148:ERROR:audio_input_processor.cc(748)] Input error
/home/pi/AIY-projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
Say "OK, Google" then speak, or press Ctrl+C to quit...
[9126:9152:ERROR:audio_input_processor.cc(748)] Input error
^C(env) pi@raspberrypi:~/AIY-projects-python/src/examples/voice $
```

Can you please help me to resolve this audio configuration issue ?

**Comment by titusece** [comment]
With the below sound card settings, I was able make it work.
Thanks for the support and wonderful link.

```
(env) pi@raspberrypi:~/$ cat ~/.asoundrc
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}

pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
```
